// ============================================================================
// DailyPulse.swift
// ============================================================================
// ETOS LLM Studio 每日脉冲核心能力
//
// 功能特性:
// - 定义每日脉冲运行记录、卡片与反馈模型
// - 提供最近聊天 / 记忆 / 请求日志的上下文拼装
// - 通过 Detached Completion 生成不污染聊天历史的每日卡片
// - 管理持久化、反馈写回、保存为会话等行为
// ============================================================================

import Foundation
import Combine
import os.log
#if os(iOS)
import UIKit
#endif

@MainActor
public final class DailyPulseManager: ObservableObject {
    public static let shared = DailyPulseManager(chatService: .shared, memoryManager: .shared)
    internal nonisolated static let persistedRetentionLimit = 14
    internal nonisolated static let feedbackHistoryRetentionLimit = 120
    internal nonisolated static let externalSignalRetentionLimit = 40
    internal nonisolated static let taskRetentionLimit = 80

    @Published public internal(set) var runs: [DailyPulseRun]
    @Published public internal(set) var feedbackHistory: [DailyPulseFeedbackEvent]
    @Published public internal(set) var pendingCuration: DailyPulseCurationNote?
    @Published public internal(set) var externalSignals: [DailyPulseExternalSignal]
    @Published public internal(set) var tasks: [DailyPulseTask]
    @Published public internal(set) var isGenerating: Bool = false
    @Published public internal(set) var lastErrorMessage: String?
    @Published public internal(set) var lastViewedDayKey: String?
    @Published public internal(set) var lastDeliveryAttemptDayKey: String?
    @Published public internal(set) var preparingDayKey: String?
    @Published public internal(set) var lastPreparationStartedAt: Date?
    @Published public var focusText: String {
        didSet {
            Self.save(focusText, forKey: Self.focusDefaultsKey, defaults: defaults)
        }
    }
    @Published public var tomorrowCurationText: String {
        didSet {
            persistPendingCurationFromDraft()
        }
    }
    @Published public var isDailyPulseEnabled: Bool {
        didSet {
            guard isDailyPulseEnabled != oldValue else { return }
            Self.save(isDailyPulseEnabled, forKey: Self.dailyPulseEnabledDefaultsKey, defaults: defaults)
            Task {
                await DailyPulseDeliveryCoordinator.shared.refreshReminderSchedule()
            }
        }
    }
    @Published public var autoGenerateEnabled: Bool {
        didSet {
            Self.save(autoGenerateEnabled, forKey: Self.autoGenerateDefaultsKey, defaults: defaults)
        }
    }
    @Published public var cardsPerRun: Int {
        didSet {
            let normalizedCount = Self.normalizedCardsPerRun(cardsPerRun)
            guard normalizedCount == cardsPerRun else {
                cardsPerRun = normalizedCount
                return
            }
            guard cardsPerRun != oldValue else { return }
            Self.save(cardsPerRun, forKey: Self.cardsPerRunDefaultsKey, defaults: defaults)
            DailyPulseDeliveryCoordinator.shared.synchronizeDeliveryTimes(to: cardsPerRun)
            let tomorrowKey = Self.nextDayKey(from: Date())
            if runs.contains(where: { $0.dayKey == tomorrowKey }) {
                runs.removeAll(where: { $0.dayKey == tomorrowKey })
                persistRuns()
                Task {
                    await DailyPulseDeliveryCoordinator.shared.refreshReminderSchedule()
                }
            }
        }
    }
    @Published public var includeMCPContext: Bool {
        didSet {
            Self.save(includeMCPContext, forKey: Self.includeMCPContextDefaultsKey, defaults: defaults)
        }
    }
    @Published public var includeShortcutContext: Bool {
        didSet {
            Self.save(includeShortcutContext, forKey: Self.includeShortcutContextDefaultsKey, defaults: defaults)
        }
    }
    @Published public var includeRecentExternalResults: Bool {
        didSet {
            Self.save(includeRecentExternalResults, forKey: Self.includeRecentExternalResultsDefaultsKey, defaults: defaults)
        }
    }
    @Published public var includeTrendContext: Bool {
        didSet {
            Self.save(includeTrendContext, forKey: Self.includeTrendContextDefaultsKey, defaults: defaults)
        }
    }

    let logger = Logger(subsystem: "com.ETOS.LLM.Studio", category: "DailyPulse")
    let chatService: ChatService
    let memoryManager: MemoryManager
    let defaults: UserDefaults
    let retentionLimit: Int
    let maxSessionsInPrompt = 4
    let maxMessagesPerSession = 6
    let maxMemoriesInPrompt = 8
    private var syncNotificationObserver: NSObjectProtocol?

    private static let dailyPulseEnabledDefaultsKey = "dailyPulse.enabled"
    private static let autoGenerateDefaultsKey = "dailyPulse.autoGenerate"
    private static let cardsPerRunDefaultsKey = "dailyPulse.cardsPerRun"
    private static let focusDefaultsKey = "dailyPulse.focusText"
    private static let includeMCPContextDefaultsKey = "dailyPulse.includeMCPContext"
    private static let includeShortcutContextDefaultsKey = "dailyPulse.includeShortcutContext"
    private static let includeRecentExternalResultsDefaultsKey = "dailyPulse.includeRecentExternalResults"
    private static let includeTrendContextDefaultsKey = "dailyPulse.includeTrendContext"
    private static let lastViewedDayKeyDefaultsKey = "dailyPulse.lastViewedDayKey"
    private static let lastDeliveryAttemptDayKeyDefaultsKey = "dailyPulse.lastDeliveryAttemptDayKey"
#if os(iOS)
    var activeBackgroundTaskIdentifier: UIBackgroundTaskIdentifier = .invalid
#endif

    public init(
        chatService: ChatService,
        memoryManager: MemoryManager,
        defaults: UserDefaults = .standard
    ) {
        self.chatService = chatService
        self.memoryManager = memoryManager
        self.defaults = defaults
        self.retentionLimit = Self.persistedRetentionLimit
        let persistedRuns = Persistence.loadDailyPulseRuns().sorted(by: { $0.generatedAt > $1.generatedAt })
        let pendingCuration = Persistence.loadDailyPulsePendingCuration()
        self.runs = Self.retainedRuns(from: persistedRuns, referenceDate: Date())
        self.feedbackHistory = Persistence.loadDailyPulseFeedbackHistory().sorted(by: { $0.createdAt > $1.createdAt })
        self.pendingCuration = pendingCuration
        self.externalSignals = Self.trimmedExternalSignals(Persistence.loadDailyPulseExternalSignals(), limit: Self.externalSignalRetentionLimit)
        self.tasks = Self.sortedTasks(Persistence.loadDailyPulseTasks())
        self.focusText = Self.textValue(forKey: Self.focusDefaultsKey, defaults: defaults, defaultValue: "")
        self.tomorrowCurationText = pendingCuration?.text ?? ""
        let storedLastViewedDayKey = Self.textValue(forKey: Self.lastViewedDayKeyDefaultsKey, defaults: defaults, defaultValue: "")
        let storedLastDeliveryAttemptDayKey = Self.textValue(forKey: Self.lastDeliveryAttemptDayKeyDefaultsKey, defaults: defaults, defaultValue: "")
        self.lastViewedDayKey = storedLastViewedDayKey.isEmpty ? nil : storedLastViewedDayKey
        self.lastDeliveryAttemptDayKey = storedLastDeliveryAttemptDayKey.isEmpty ? nil : storedLastDeliveryAttemptDayKey
        self.isDailyPulseEnabled = Self.boolValue(forKey: Self.dailyPulseEnabledDefaultsKey, defaults: defaults, defaultValue: true)
        self.autoGenerateEnabled = Self.boolValue(forKey: Self.autoGenerateDefaultsKey, defaults: defaults, defaultValue: true)
        let storedCardsPerRun = Self.integerValue(forKey: Self.cardsPerRunDefaultsKey, defaults: defaults, defaultValue: 3)
        self.cardsPerRun = Self.normalizedCardsPerRun(storedCardsPerRun)
        self.includeMCPContext = Self.boolValue(forKey: Self.includeMCPContextDefaultsKey, defaults: defaults, defaultValue: true)
        self.includeShortcutContext = Self.boolValue(forKey: Self.includeShortcutContextDefaultsKey, defaults: defaults, defaultValue: true)
        self.includeRecentExternalResults = Self.boolValue(forKey: Self.includeRecentExternalResultsDefaultsKey, defaults: defaults, defaultValue: false)
        self.includeTrendContext = Self.boolValue(forKey: Self.includeTrendContextDefaultsKey, defaults: defaults, defaultValue: true)
        if cardsPerRun != storedCardsPerRun {
            Self.save(cardsPerRun, forKey: Self.cardsPerRunDefaultsKey, defaults: defaults)
        }
        prunePendingCurationIfNeeded(referenceDate: Date())
        if runs.count != persistedRuns.count {
            Persistence.saveDailyPulseRuns(runs)
        }
        if externalSignals.count != Persistence.loadDailyPulseExternalSignals().count {
            Persistence.saveDailyPulseExternalSignals(externalSignals)
        }
        if tasks != Self.sortedTasks(Persistence.loadDailyPulseTasks()) {
            Persistence.saveDailyPulseTasks(tasks)
        }

        syncNotificationObserver = NotificationCenter.default.addObserver(
            forName: .syncDailyPulseUpdated,
            object: nil,
            queue: .main
        ) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.reloadPersistedRuns()
            }
        }
    }

    deinit {
        if let syncNotificationObserver {
            NotificationCenter.default.removeObserver(syncNotificationObserver)
        }
    }

    private static func usesDatabase(defaults: UserDefaults) -> Bool {
        defaults === UserDefaults.standard
    }

    private static func boolValue(forKey key: String, defaults: UserDefaults, defaultValue: Bool) -> Bool {
        guard usesDatabase(defaults: defaults) else {
            return defaults.object(forKey: key) as? Bool ?? defaultValue
        }
        AppConfigLegacyUserDefaultsMigration.migrateStandardUserDefaults()
        if let stored = Persistence.readAppConfigInteger(key: key) {
            return stored != 0
        }
        return defaultValue
    }

    private static func textValue(forKey key: String, defaults: UserDefaults, defaultValue: String) -> String {
        guard usesDatabase(defaults: defaults) else {
            return defaults.string(forKey: key) ?? defaultValue
        }
        AppConfigLegacyUserDefaultsMigration.migrateStandardUserDefaults()
        if let stored = Persistence.readAppConfigText(key: key) {
            return stored
        }
        return defaultValue
    }

    private static func integerValue(forKey key: String, defaults: UserDefaults, defaultValue: Int) -> Int {
        guard usesDatabase(defaults: defaults) else {
            return defaults.object(forKey: key) as? Int ?? defaultValue
        }
        AppConfigLegacyUserDefaultsMigration.migrateStandardUserDefaults()
        return Persistence.readAppConfigInteger(key: key) ?? defaultValue
    }

    private static func save(_ value: Bool, forKey key: String, defaults: UserDefaults) {
        guard usesDatabase(defaults: defaults) else {
            defaults.set(value, forKey: key)
            return
        }
        Persistence.writeAppConfig(key: key, integer: value ? 1 : 0, typeHint: "bool")
    }

    private static func save(_ value: String, forKey key: String, defaults: UserDefaults) {
        guard usesDatabase(defaults: defaults) else {
            defaults.set(value, forKey: key)
            return
        }
        Persistence.writeAppConfig(key: key, text: value, typeHint: "text")
    }

    private static func save(_ value: Int, forKey key: String, defaults: UserDefaults) {
        guard usesDatabase(defaults: defaults) else {
            defaults.set(value, forKey: key)
            return
        }
        Persistence.writeAppConfig(key: key, integer: value, typeHint: "integer")
    }

    public nonisolated static let minimumCardsPerRun = 1
    public nonisolated static let maximumCardsPerRun = 6

    public nonisolated static func normalizedCardsPerRun(_ count: Int) -> Int {
        min(max(count, minimumCardsPerRun), maximumCardsPerRun)
    }

    var candidateCardsPerRun: Int {
        cardsPerRun * 2
    }

    public var latestRun: DailyPulseRun? {
        todayRun
    }

    public var todayRun: DailyPulseRun? {
        runs.first(where: { $0.dayKey == Self.dayKey(for: Date()) })
    }

    public var tomorrowRun: DailyPulseRun? {
        runs.first(where: { $0.dayKey == Self.nextDayKey(from: Date()) })
    }

    public var archivedRuns: [DailyPulseRun] {
        []
    }

    public var primaryRun: DailyPulseRun? {
        todayRun
    }

    internal func notificationTarget(
        runID: UUID?,
        cardID: UUID?,
        dayKey: String?
    ) -> (runID: UUID, card: DailyPulseCard)? {
        if let runID,
           let run = runs.first(where: { $0.id == runID }) {
            if let cardID,
               let card = run.cards.first(where: { $0.id == cardID }) {
                return (runID, card)
            }
            if let fallbackCard = run.visibleCards.first ?? run.cards.first {
                return (runID, fallbackCard)
            }
        }

        let candidateRuns: [DailyPulseRun]
        if let dayKey, !dayKey.isEmpty {
            candidateRuns = runs
                .filter { $0.dayKey == dayKey }
                .sorted(by: { $0.generatedAt > $1.generatedAt })
        } else if let primaryRun {
            candidateRuns = [primaryRun]
        } else {
            candidateRuns = runs.sorted(by: { $0.generatedAt > $1.generatedAt })
        }

        for run in candidateRuns {
            if let fallbackCard = run.visibleCards.first ?? run.cards.first {
                return (run.id, fallbackCard)
            }
        }
        return nil
    }

    public var hasUnviewedTodayRun: Bool {
        Self.hasUnviewedRun(todayRunDayKey: todayRun?.dayKey, lastViewedDayKey: lastViewedDayKey)
    }

    public var isPreparingTodayPulse: Bool {
        Self.isPreparingPulse(
            preparingDayKey: preparingDayKey,
            todayRunDayKey: todayRun?.dayKey,
            referenceDate: Date()
        )
    }

    public var isPreparingTomorrowPulse: Bool {
        preparingDayKey == Self.nextDayKey(from: Date()) && tomorrowRun == nil
    }

    public var feedbackHistoryPreview: [DailyPulseFeedbackEvent] {
        Array(feedbackHistory.prefix(5))
    }

    public var externalSignalPreview: [DailyPulseExternalSignal] {
        Array(externalSignals.prefix(5))
    }

    public var pendingTasks: [DailyPulseTask] {
        tasks.filter { !$0.isCompleted }
    }

    public var completedTasksPreview: [DailyPulseTask] {
        Array(tasks.filter(\.isCompleted).prefix(3))
    }

    public var nextCurationTargetDayKey: String {
        Self.nextDayKey(from: Date())
    }

    public func reloadPersistedRuns() {
        let persistedRuns = Persistence.loadDailyPulseRuns().sorted(by: { $0.generatedAt > $1.generatedAt })
        let retainedRuns = Self.retainedRuns(from: persistedRuns, referenceDate: Date())
        runs = retainedRuns
        feedbackHistory = Persistence.loadDailyPulseFeedbackHistory().sorted(by: { $0.createdAt > $1.createdAt })
        let latestPending = Persistence.loadDailyPulsePendingCuration()
        pendingCuration = latestPending
        tomorrowCurationText = latestPending?.text ?? ""
        externalSignals = Self.trimmedExternalSignals(
            Persistence.loadDailyPulseExternalSignals(),
            limit: Self.externalSignalRetentionLimit
        )
        tasks = Self.sortedTasks(Persistence.loadDailyPulseTasks())
        reloadSettingsFromStorage()
        if runs != persistedRuns {
            Persistence.saveDailyPulseRuns(runs)
        }
        Task {
            await DailyPulseDeliveryCoordinator.shared.refreshReminderSchedule()
        }
    }

    public func reloadSettingsFromStorage() {
        focusText = Self.textValue(forKey: Self.focusDefaultsKey, defaults: defaults, defaultValue: "")
        let storedLastViewedDayKey = Self.textValue(forKey: Self.lastViewedDayKeyDefaultsKey, defaults: defaults, defaultValue: "")
        let storedLastDeliveryAttemptDayKey = Self.textValue(forKey: Self.lastDeliveryAttemptDayKeyDefaultsKey, defaults: defaults, defaultValue: "")
        lastViewedDayKey = storedLastViewedDayKey.isEmpty ? nil : storedLastViewedDayKey
        lastDeliveryAttemptDayKey = storedLastDeliveryAttemptDayKey.isEmpty ? nil : storedLastDeliveryAttemptDayKey
        isDailyPulseEnabled = Self.boolValue(forKey: Self.dailyPulseEnabledDefaultsKey, defaults: defaults, defaultValue: true)
        autoGenerateEnabled = Self.boolValue(forKey: Self.autoGenerateDefaultsKey, defaults: defaults, defaultValue: true)
        cardsPerRun = Self.normalizedCardsPerRun(
            Self.integerValue(forKey: Self.cardsPerRunDefaultsKey, defaults: defaults, defaultValue: 3)
        )
        includeMCPContext = Self.boolValue(forKey: Self.includeMCPContextDefaultsKey, defaults: defaults, defaultValue: true)
        includeShortcutContext = Self.boolValue(forKey: Self.includeShortcutContextDefaultsKey, defaults: defaults, defaultValue: true)
        includeRecentExternalResults = Self.boolValue(forKey: Self.includeRecentExternalResultsDefaultsKey, defaults: defaults, defaultValue: false)
        includeTrendContext = Self.boolValue(forKey: Self.includeTrendContextDefaultsKey, defaults: defaults, defaultValue: true)
    }

    public func clearError() {
        lastErrorMessage = nil
    }

    public func clearFeedbackHistory() {
        feedbackHistory = []
        Persistence.saveDailyPulseFeedbackHistory(feedbackHistory)
    }

    public func clearExternalSignals() {
        externalSignals = []
        Persistence.saveDailyPulseExternalSignals(externalSignals)
    }

    public func removeFeedbackHistoryEvent(id: UUID) {
        feedbackHistory = Self.removingFeedbackEvent(id: id, from: feedbackHistory)
        Persistence.saveDailyPulseFeedbackHistory(feedbackHistory)
    }

    public func removeExternalSignal(id: UUID) {
        externalSignals = Self.removingExternalSignal(id: id, from: externalSignals)
        Persistence.saveDailyPulseExternalSignals(externalSignals)
    }

    public func clearTomorrowCuration() {
        tomorrowCurationText = ""
    }

    public func clearCompletedTasks() {
        tasks.removeAll(where: \.isCompleted)
        persistTasks()
    }

    public func removeTask(id: UUID) {
        tasks = tasks.filter { $0.id != id }
        persistTasks()
    }

    public func markTodayRunViewed(referenceDate: Date = Date()) {
        let todayKey = Self.dayKey(for: referenceDate)
        guard todayRun?.dayKey == todayKey else { return }
        guard lastViewedDayKey != todayKey else { return }
        lastViewedDayKey = todayKey
        Self.save(todayKey, forKey: Self.lastViewedDayKeyDefaultsKey, defaults: defaults)
    }

    internal func beginPreparation(dayKey: String, referenceDate: Date = Date()) {
        preparingDayKey = dayKey
        lastPreparationStartedAt = referenceDate
    }

    internal func finishPreparation() {
        preparingDayKey = nil
    }

    public func generateForScheduledDeliveryIfNeeded(
        reminderEnabled: Bool,
        deliveryTimes: [DailyPulseDeliveryTime],
        referenceDate: Date = Date()
    ) async {
        guard isDailyPulseEnabled else { return }

        let todayKey = Self.dayKey(for: referenceDate)
        if Self.shouldProcessScheduledDelivery(
            reminderEnabled: reminderEnabled,
            deliveryTimes: deliveryTimes,
            referenceDate: referenceDate,
            lastDeliveryAttemptDayKey: lastDeliveryAttemptDayKey
        ) {
            lastDeliveryAttemptDayKey = todayKey
            Self.save(todayKey, forKey: Self.lastDeliveryAttemptDayKeyDefaultsKey, defaults: defaults)

            if Self.shouldUseExistingRunForScheduledDelivery(
                todayRunDayKey: todayRun?.dayKey,
                referenceDate: referenceDate
            ) {
                await DailyPulseDeliveryCoordinator.shared.refreshReminderSchedule(referenceDate: referenceDate)
            } else {
                let shouldNotifyReady = !DailyPulseDeliveryCoordinator.hasFutureDeliveryTime(
                    dayKey: todayKey,
                    deliveryTimes: deliveryTimes,
                    referenceDate: referenceDate
                )
                await generate(
                    force: false,
                    trigger: .delivery,
                    targetDayKey: todayKey,
                    notifyReadyWhenFinished: shouldNotifyReady
                )
            }
        }

        await generateTomorrowForDeliveryIfNeeded(
            reminderEnabled: reminderEnabled,
            referenceDate: referenceDate
        )
    }

    @discardableResult
    public func generateForBackgroundDeliveryIfNeeded(
        reminderEnabled: Bool,
        deliveryTimes: [DailyPulseDeliveryTime],
        referenceDate: Date = Date()
    ) async -> Bool {
        guard isDailyPulseEnabled else { return false }
        guard reminderEnabled else { return false }

        if Self.hasReachedTomorrowPreparationTime(referenceDate: referenceDate) {
            let tomorrowKey = Self.nextDayKey(from: referenceDate)
            if !runs.contains(where: { $0.dayKey == tomorrowKey }) {
                await generate(
                    force: false,
                    trigger: .delivery,
                    targetDayKey: tomorrowKey
                )
            }
            return runs.contains(where: { $0.dayKey == tomorrowKey })
        }

        let todayKey = Self.dayKey(for: referenceDate)
        let hasTodayRun = runs.contains(where: { $0.dayKey == todayKey })

        if !hasTodayRun {
            let shouldNotifyReady = !DailyPulseDeliveryCoordinator.hasFutureDeliveryTime(
                dayKey: todayKey,
                deliveryTimes: deliveryTimes,
                referenceDate: referenceDate,
                calendar: Calendar(identifier: .gregorian)
            )
            await generate(
                force: false,
                trigger: .delivery,
                targetDayKey: todayKey,
                notifyReadyWhenFinished: shouldNotifyReady
            )
            return runs.contains(where: { $0.dayKey == todayKey })
        }
        return true
    }

    private func generateTomorrowForDeliveryIfNeeded(
        reminderEnabled: Bool,
        referenceDate: Date
    ) async {
        guard reminderEnabled else { return }
        guard Self.hasReachedTomorrowPreparationTime(referenceDate: referenceDate) else { return }
        let tomorrowKey = Self.nextDayKey(from: referenceDate)
        guard !runs.contains(where: { $0.dayKey == tomorrowKey }) else { return }
        await generate(
            force: false,
            trigger: .delivery,
            targetDayKey: tomorrowKey
        )
    }

    public func generateIfNeeded(trigger: DailyPulseTrigger = .automatic) async {
        guard isDailyPulseEnabled else { return }
        if trigger == .automatic, !autoGenerateEnabled {
            return
        }
        let todayKey = Self.dayKey(for: Date())
        if trigger == .automatic, runs.contains(where: { $0.dayKey == todayKey }) {
            return
        }
        await generate(force: trigger == .manual, trigger: trigger)
    }

    public func generateNow() async {
        await generate(force: true, trigger: .manual)
    }

    public func applyFeedback(_ feedback: DailyPulseCardFeedback, cardID: UUID, runID: UUID) {
        let run = runs.first(where: { $0.id == runID })
        let targetCard = run?.cards.first(where: { $0.id == cardID })
        runs = Self.applyingFeedback(feedback, to: cardID, runID: runID, in: runs)
        persistRuns()
        if feedback == .hidden {
            Task {
                await DailyPulseDeliveryCoordinator.shared.refreshReminderSchedule()
            }
        }
        if let action = Self.historyAction(for: feedback),
           let run,
           let targetCard {
            appendFeedbackEvent(
                .init(
                    dayKey: run.dayKey,
                    topicHint: Self.topicText(for: targetCard),
                    cardTitle: targetCard.title,
                    action: action
                )
            )
        }
    }

    @discardableResult
    public func saveCardAsSession(cardID: UUID, runID: UUID) -> ChatSession? {
        guard let run = runs.first(where: { $0.id == runID }),
              let card = card(cardID: cardID, runID: runID) else { return nil }
        let hadSavedSession = card.savedSessionID != nil
        let content = Self.archivedChatContent(for: card)
        let session = chatService.createSavedSession(
            name: card.title,
            initialMessages: [ChatMessage(role: .assistant, content: content)]
        )
        runs = Self.markingCardSaved(sessionID: session.id, cardID: cardID, runID: runID, in: runs)
        persistRuns()
        if !hadSavedSession {
            appendFeedbackEvent(
                .init(
                    dayKey: run.dayKey,
                    topicHint: Self.topicText(for: card),
                    cardTitle: card.title,
                    action: .saved
                )
            )
        }
        return session
    }

    public func linkedTask(cardID: UUID, runID: UUID) -> DailyPulseTask? {
        guard let run = runs.first(where: { $0.id == runID }) else { return nil }
        return tasks.first(where: { $0.sourceCardID == cardID && $0.sourceDayKey == run.dayKey })
    }

    @discardableResult
    public func addTaskFromCard(cardID: UUID, runID: UUID) -> DailyPulseTask? {
        guard let run = runs.first(where: { $0.id == runID }),
              let card = card(cardID: cardID, runID: runID) else { return nil }

        if let existing = tasks.first(where: { $0.sourceCardID == cardID && $0.sourceDayKey == run.dayKey }) {
            return existing
        }

        let now = Date()
        let task = DailyPulseTask(
            sourceDayKey: run.dayKey,
            sourceCardID: card.id,
            title: card.title,
            details: card.summary,
            suggestedPrompt: card.suggestedPrompt,
            createdAt: now,
            updatedAt: now
        )
        tasks = Self.sortedTasks([task] + tasks)
        persistTasks()
        return task
    }

    public func toggleTaskCompletion(id: UUID) {
        let now = Date()
        tasks = tasks.map { task in
            guard task.id == id else { return task }
            var updated = task
            updated.completedAt = task.isCompleted ? nil : now
            updated.updatedAt = now
            return updated
        }
        tasks = Self.sortedTasks(tasks)
        persistTasks()
    }

    public func appendExternalSignal(_ signal: DailyPulseExternalSignal) {
        externalSignals = Self.appendingExternalSignal(
            signal,
            to: externalSignals,
            limit: Self.externalSignalRetentionLimit
        )
        Persistence.saveDailyPulseExternalSignals(externalSignals)
    }

    public func ingestAnnouncements(_ announcements: [Announcement]) {
        let nextHistory = Self.syncingAnnouncementSignals(
            announcements,
            in: externalSignals,
            limit: Self.externalSignalRetentionLimit
        )
        guard nextHistory != externalSignals else { return }
        externalSignals = nextHistory
        Persistence.saveDailyPulseExternalSignals(externalSignals)
    }
}
